# -*- coding: utf-8 -*-
"""Copy of Timezone Conversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1spTymEah2iL2bl3PH4O3YOvcCNIV0QxX
"""

from IPython.display import HTML, display

html_code = """
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Singapore and Minnesota Clocks</title>
    <style>
      body {
        font-family: Arial, sans-serif;
        font-size: 28px;
        text-align: center;
        padding-top: 60px;
        background-color: #f4f4f4;
      }
      #sg-clock, #mn-clock {
        margin: 20px 0;
        color: #333;
      }
    </style>
    <script>
      function updateClocks() {
        const sgOptions = {
          timeZone: 'Asia/Singapore',
          weekday: 'long',
          year: 'numeric',
          month: 'short',
          day: '2-digit',
          hour: 'numeric',
          minute: '2-digit',
          second: '2-digit',
          hour12: true
        };

        const mnOptions = {
          timeZone: 'America/Chicago',
          weekday: 'long',
          year: 'numeric',
          month: 'short',
          day: '2-digit',
          hour: 'numeric',
          minute: '2-digit',
          second: '2-digit',
          hour12: true
        };

        const sgTime = new Date().toLocaleString('en-US', sgOptions);
        const mnTime = new Date().toLocaleString('en-US', mnOptions);

        document.getElementById("sg-clock").innerHTML = "Singapore: " + sgTime;
        document.getElementById("mn-clock").innerHTML = "Minnesota: " + mnTime;
      }

      setInterval(updateClocks, 1000);
    </script>
  </head>
  <body onload="updateClocks()">
    <div id="sg-clock">Loading Singapore time...</div>
    <div id="mn-clock">Loading Minnesota time...</div>
  </body>
</html>
"""

display(HTML(html_code))

from IPython.display import IFrame

IFrame('https://drive.google.com/file/d/1F_8UqemQ7WcACeuXOnNcmXetxXPPpG-9/view?usp=sharing', width=700, height=400)

from IPython.display import HTML, display

html = """
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Schedule</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      background-color: #fdfdfd;
    }
    #sg-clock, #mn-clock {
      text-align: center;
      font-size: 28px;
      margin-top: 20px;
      color: #333;
    }
    h2 {
      text-align: center;
      color: red;
      margin-top: 40px;
    }
    table {
      border-collapse: collapse;
      width: 95%;
      margin: 30px auto;
    }
    th, td {
      border: 1px solid #ccc;
      padding: 12px;
      text-align: left;
      vertical-align: top;
    }
    th {
      background-color: #f2f2f2;
    }
    .on-leave, .pm-leave {
      background-color: #fff8b3;
    }
    .mn-pink {
      background-color: #ffd6e8;
    }
    .mn-yellow {
      background-color: #fdf3b1;
    }
  </style>
  <script>
    function updateClocks() {
      const sgOptions = {
        timeZone: 'Asia/Singapore',
        weekday: 'long',
        year: 'numeric',
        month: 'short',
        day: '2-digit',
        hour: 'numeric',
        minute: '2-digit',
        hour12: true
      };
      const mnOptions = {
        timeZone: 'America/Chicago',
        weekday: 'long',
        year: 'numeric',
        month: 'short',
        day: '2-digit',
        hour: 'numeric',
        minute: '2-digit',
        hour12: true
      };
      document.getElementById("sg-clock").innerHTML = "🇸🇬 Singapore: " + new Date().toLocaleString('en-US', sgOptions);
      document.getElementById("mn-clock").innerHTML = "🇺🇸 Minnesota: " + new Date().toLocaleString('en-US', mnOptions);
    }
    setInterval(updateClocks, 1000);
  </script>
</head>
<body onload="updateClocks()">
  <div id="sg-clock">Loading Singapore time...</div>
  <div id="mn-clock">Loading Minnesota time...</div>

  <h2>⚠️ Alert: July 2025 Schedule</h2>
  <table>
    <tr>
      <th>Date</th>
      <th>Event (SGT)</th>
      <th>MN Time</th>
    </tr>
<tr><td>5 July</td>
  <td>Not working</td>
  <td class="mn-yellow"></td>
</tr>

<tr><td>6 July</td>
  <td>Not working</td>
  <td class="mn-yellow"></td>
</tr>
    <tr>
      <td>7 July</td>
<td class="pm-leave">
  Work SGT 8:30am – 12:30pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 06 Jul 7:30pm – 11:30pm<br><br>

  Meeting SGT 12:30pm – 1:00pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 06 Jul 11:30pm – 12:00am<br><br>

  PM Leave SGT 1:00pm – 5:30pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 07 Jul 12:00am – 4:30am<br><br>

  Capstone SGT 9:00am – 6:00pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 06 Jul 8:00pm – 07 Jul 5:00am
</td>

      <td class="mn-pink">Baby working on MN timezone</td>
    </tr>
  <tr><td>8 July</td>
  <td>
    Meetings SGT 11:00am<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 07 Jul 10:00pm<br><br>

    Meetings SGT 3:00pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 08 Jul 2:00am
  </td>
  <td class="mn-pink">Baby working on MN timezone</td>
</tr>

<tr><td>9 July</td>
  <td>
    Meeting SGT 3:00pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 09 Jul 2:00am
  </td>
  <td class="mn-yellow"></td>
</tr>

<tr><td>10 July</td>
  <td class="on-leave">
    On Leave<br>
    </td>
  <td class="mn-yellow"></td>
</tr>

<tr><td>11 July</td>
  <td class="pm-leave">
    Work SGT 8:30am – 12:30pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 06 Jul 7:30pm – 11:30pm<br><br>

    PM Leave SGT 12:30pm – 5:30pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 11 Jul 11:30pm – 4:30am<br><br>

   // Capstone Presentation SGT 11:00am – 11:40am<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 10 Jul 10:00pm – 10:40pm
  </td>
  <td class="mn-pink">Baby working on MN timezone</td>
</tr>
    <tr><td>12 July</td><td> Not working</td><td class="mn-pink">Baby working on MN timezone</td></tr>
    <tr><td>13 July</td><td>Not working</td><td class="mn-pink">Baby working on MN timezone</td></tr>
   <tr><td>14 July</td>
  <td>
    Capstone SGT 9:00am – 6:00pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 13 Jul 8:00pm – 14 Jul 5:00am<br><br>

    Meeting SGT 1:30pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 14 Jul 12:30am
  </td>
  <td class="mn-yellow"></td>
</tr>
  <tr><td>15 July</td><td class="pm-leave">On Leave<br>> MN Timezone: 14 Jul</td><td class="mn-yellow"></td></tr>
    <tr><td>16 July</td><td class="pm-leave">On Leave<br>> MN Timezone: 15 Jul</td><td class="mn-pink">Baby working on MN timezone</td></tr>
    <tr><td>17 July</td><td> Work SGT 8:30am – 5:30pm<br>
  &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 16 Jul 7:30pm – 4:30am<br><br></td><td class="mn-pink">Baby working on MN timezone</td></tr>
<tr><td>18 July</td>
  <td>
    Meeting SGT 2:30pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 17 Jul 1:30am
  </td>
  <td class="mn-yellow"></td>    <tr><td>19 July</td><td> Not working</td><td class="mn-yellow"></td></tr>
    <tr><td>20 July</td><td> Not working</td><td class="mn-yellow"></td></tr>
    <tr><td>21 July</td><td class="pm-leave">On Leave</td><td class="mn-pink">Baby working on MN timezone</td></tr>
 <tr><td>22 July</td>
  <td>
    Meeting SGT 11:00am<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 21 Jul 10:00pm<br><br>

    Meeting SGT 3:00pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 22 Jul 2:00am
  </td>
  <td class="mn-pink">Baby working on MN timezone</td>
</tr>
   <tr><td>23 July</td>
  <td>
      Meeting SGT 3:00pm<br>
    &nbsp;&nbsp;&nbsp;&nbsp;> MN Timezone: 23 Jul 2:00am
  </td>
  <td class="mn-yellow">Baby working on MN timezone</td>
</tr>

   <tr><td>24 July</td><td class="on-leave">On Leave</td><td class="mn-yellow"></td></tr>
    <tr><td>25 July</td><td class="on-leave">On Leave</td><td></td></tr>
  </table>
</body>
</html>
"""

display(HTML(html))

